import { useEffect,useState } from "react";
import { CheckCircle,BookOpen,ThumbsUp,ThumbsDown,TriangleAlert } from "lucide-react";
import { AppLayout } from "@/layouts/AppLayout"; import { useAuthStore } from "@/store/authStore"; import { fetchDashboard } from "@/services/dashboardService"; import { createAttendance,updateAttendance } from "@/services/attendanceService"; import type { DashboardData,TodayLecture } from "@/types/dashboard"; import { useToast } from "@/components/toast/useToast"; import { Button } from "@/components/ui/button";
import { StatCard } from "@/components/dashboard/StatCard"; import { OverallAttendanceChart } from "@/components/dashboard/OverallAttendanceChart"; import { SubjectSelector } from "@/components/dashboard/SubjectSelector"; import { SubjectAttendanceCard } from "@/components/dashboard/SubjectAttendanceCard"; import { TodayClasses } from "@/components/dashboard/TodayClasses"; import { QuickActions } from "@/components/dashboard/QuickActions"; import { DashboardSkeleton } from "@/components/dashboard/DashboardSkeleton"; import { DashboardEmptyState } from "@/components/dashboard/DashboardEmptyState";
const date=()=>new Date().toLocaleDateString("en-CA");
export function DashboardPage(){const user=useAuthStore(s=>s.user);const {showToast}=useToast();const [data,setData]=useState<DashboardData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [selected,setSelected]=useState("");
 const load=async()=>{setLoading(true);setError(false);try{const r=await fetchDashboard();setData(r.data!)}catch{setError(true)}finally{setLoading(false)}}; useEffect(()=>{void load()},[]);
 const mark=async(l:TodayLecture,status:"PRESENT"|"ABSENT")=>{try{if(l.attendanceId)await updateAttendance(l.attendanceId,{status});else await createAttendance({subjectId:l.subjectId,timetableLectureId:l.id,date:date(),status});showToast("Attendance updated successfully.","success");await load()}catch(e){showToast(e instanceof Error?e.message:"Could not update attendance","error")}};
 const subject=data?.subjectAttendance.find(s=>s.subjectId===selected);
 return <AppLayout><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 sm:py-10"><div><h1 className="font-display text-3xl text-forest-dark">Welcome back, {user?.name}</h1><p className="mt-1 text-muted">Here's how your attendance is looking today.</p></div>{loading?<div className="mt-8"><DashboardSkeleton/></div>:error?<div className="mt-8 rounded-card border border-border bg-white p-10 text-center"><TriangleAlert className="mx-auto text-[#C0392B]"/><p className="mt-3 text-muted">Unable to load your dashboard.</p><Button className="mt-4" onClick={load}>Retry</Button></div>:data?<><div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Overall Attendance" value={data.overallAttendance} accent icon={<CheckCircle size={20}/>}/><StatCard label="Total Lectures" value={data.totalLectures} icon={<BookOpen size={20}/>}/><StatCard label="Present" value={data.presentLectures} icon={<ThumbsUp size={20}/>}/><StatCard label="Absent" value={data.absentLectures} icon={<ThumbsDown size={20}/>}/></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><OverallAttendanceChart percentage={data.overallAttendance} present={data.presentLectures} absent={data.absentLectures} total={data.totalLectures}/><div><section className="rounded-card border border-border bg-white p-6"><h2 className="font-display text-xl text-forest-dark">Subject-wise Attendance</h2><SubjectSelector subjects={data.subjectAttendance} value={selected} onChange={setSelected}/></section><div className="mt-4"><SubjectAttendanceCard subject={subject}/></div></div></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><TodayClasses lectures={data.todayLectures} onMark={mark}/><QuickActions/></div>{data.subjectAttendance.length===0&&<div className="mt-6"><DashboardEmptyState message="Add subjects to start tracking attendance."/></div>}{data.totalLectures===0&&data.subjectAttendance.length>0&&<div className="mt-6"><DashboardEmptyState message="Start marking attendance to see your progress."/></div>}</>:null}</div></AppLayout>}
