import { useEffect, useState } from "react";
import { LogOut, Save, UserCircle } from "lucide-react";
import { AppLayout } from "@/layouts/AppLayout";
import { useAuthStore } from "@/store/authStore";
import { getProfile, updateProfile } from "@/services/profileService";
import { useToast } from "@/components/toast/useToast";
import { ErrorState } from "@/components/ui/ErrorState";
import { useNavigate } from "react-router-dom";
export function ProfilePage(){const user=useAuthStore(s=>s.user); const logout=useAuthStore(s=>s.logout); const {showToast}=useToast(); const nav=useNavigate(); const [name,setName]=useState(user?.name||""); const [image,setImage]=useState(user?.profileImage||""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(false);
 const load=async()=>{setLoading(true);setError(false);try{const r=await getProfile();setName(r.data.user.name);setImage(r.data.user.profileImage||"");}catch{setError(true)}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const r=await updateProfile({name,profileImage:image||null}); useAuthStore.setState({user:r.data.user});showToast("Profile updated successfully","success")}catch(e){showToast(e instanceof Error?e.message:"Unable to update profile","error")}finally{setSaving(false)}};
 const doLogout=async()=>{await logout();showToast("You've been logged out.","info");nav("/")};
 return <AppLayout><div className="mx-auto max-w-3xl p-4 sm:p-6 lg:p-10"><h1 className="font-display text-3xl text-forest-dark">Profile</h1><p className="mt-1 text-muted">Manage your personal information.</p>{loading?<div className="mt-6 animate-pulse rounded-2xl bg-white p-8 h-96"/>:error?<div className="mt-6"><ErrorState title="Unable to load your profile" onRetry={load}/></div>:<form onSubmit={save} className="mt-6 rounded-2xl border border-border bg-white p-5 sm:p-8"><div className="flex flex-col items-center gap-3 sm:flex-row sm:items-start"><div className="flex h-20 w-20 items-center justify-center overflow-hidden rounded-full bg-light-green text-forest">{image?<img src={image} alt="Profile" className="h-full w-full object-cover"/>:<UserCircle size={48}/>}</div><div><h2 className="font-display text-xl text-forest-dark">{name}</h2><p className="text-sm text-muted">{user?.email}</p></div></div><label className="mt-6 block text-sm font-medium text-forest-dark">Name<input aria-label="Name" value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-lg border border-border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-forest" required/></label><label className="mt-4 block text-sm font-medium text-forest-dark">Profile image URL<input aria-label="Profile image URL" type="url" value={image} onChange={e=>setImage(e.target.value)} placeholder="https://example.com/photo.jpg" className="mt-2 w-full rounded-lg border border-border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-forest"/></label><div className="mt-6 flex flex-wrap gap-3"><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-forest px-4 py-2.5 text-white disabled:opacity-50"><Save size={16}/>{saving?"Saving...":"Save changes"}</button><button type="button" onClick={doLogout} className="inline-flex items-center gap-2 rounded-lg bg-cream px-4 py-2.5 text-forest-dark"><LogOut size={16}/>Logout</button></div></form>}</div></AppLayout>}
